#!/usr/bin/env python

import node_manager_daemon_fkie
node_manager_daemon_fkie.start_client()

# 
# def run():
#     channel = grpc.insecure_channel('localhost:50051')
#     launch_stub = LaunchManagerServiceStub(channel)
#     launch_response = launch_stub.ListPath(ListPathRequest(path=""))
#     print("for path %s:" % launch_response.path)
#     for p in launch_response.item:
#         print("  %s [%d]" % (p.path, p.type))
#         if p.type in [1, 3]:
#             launch_response2 = launch_stub.ListPath(ListPathRequest(path=p.path))
#             for p2 in launch_response2.item:
#                 print("    %s [%d]" % (p2.path, p2.type))
# 
# if __name__ == '__main__':
#     run()
