# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingsDockWidget.ui'
#
# Created: Wed May 28 11:28:29 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(451, 497)
        DockWidget.setFloating(False)
        DockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 441, 312))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameUser = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameUser.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameUser.setFrameShadow(QtGui.QFrame.Raised)
        self.frameUser.setObjectName("frameUser")
        self.gridLayout_2 = QtGui.QGridLayout(self.frameUser)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.defaultUserLabel = QtGui.QLabel(self.frameUser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultUserLabel.sizePolicy().hasHeightForWidth())
        self.defaultUserLabel.setSizePolicy(sizePolicy)
        self.defaultUserLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.defaultUserLabel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.defaultUserLabel.setObjectName("defaultUserLabel")
        self.gridLayout_2.addWidget(self.defaultUserLabel, 0, 0, 1, 1)
        self.defaultUserEdit = QtGui.QLineEdit(self.frameUser)
        self.defaultUserEdit.setObjectName("defaultUserEdit")
        self.gridLayout_2.addWidget(self.defaultUserEdit, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frameUser)
        self.framePath = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.framePath.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePath.setFrameShadow(QtGui.QFrame.Raised)
        self.framePath.setObjectName("framePath")
        self.gridLayout = QtGui.QGridLayout(self.framePath)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.settingsPathLabel = QtGui.QLabel(self.framePath)
        self.settingsPathLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.settingsPathLabel.setObjectName("settingsPathLabel")
        self.gridLayout.addWidget(self.settingsPathLabel, 0, 0, 1, 1)
        self.settingsPathEdit = QtGui.QLineEdit(self.framePath)
        self.settingsPathEdit.setObjectName("settingsPathEdit")
        self.gridLayout.addWidget(self.settingsPathEdit, 0, 1, 1, 1)
        self.settingsPathButton = QtGui.QPushButton(self.framePath)
        self.settingsPathButton.setFlat(True)
        self.settingsPathButton.setObjectName("settingsPathButton")
        self.gridLayout.addWidget(self.settingsPathButton, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.framePath)
        self.frameRobotPath = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameRobotPath.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameRobotPath.setFrameShadow(QtGui.QFrame.Raised)
        self.frameRobotPath.setObjectName("frameRobotPath")
        self.gridLayout_3 = QtGui.QGridLayout(self.frameRobotPath)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.robotPathEdit = QtGui.QLineEdit(self.frameRobotPath)
        self.robotPathEdit.setObjectName("robotPathEdit")
        self.gridLayout_3.addWidget(self.robotPathEdit, 0, 1, 1, 1)
        self.robotPathButton = QtGui.QPushButton(self.frameRobotPath)
        self.robotPathButton.setFlat(True)
        self.robotPathButton.setObjectName("robotPathButton")
        self.gridLayout_3.addWidget(self.robotPathButton, 0, 2, 1, 1)
        self.robotPathLabel = QtGui.QLabel(self.frameRobotPath)
        self.robotPathLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.robotPathLabel.setObjectName("robotPathLabel")
        self.gridLayout_3.addWidget(self.robotPathLabel, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frameRobotPath)
        self.frameLaunchHistoryLength = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameLaunchHistoryLength.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameLaunchHistoryLength.setFrameShadow(QtGui.QFrame.Raised)
        self.frameLaunchHistoryLength.setObjectName("frameLaunchHistoryLength")
        self.gridLayout_4 = QtGui.QGridLayout(self.frameLaunchHistoryLength)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.launchHistoryLengthLabel = QtGui.QLabel(self.frameLaunchHistoryLength)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.launchHistoryLengthLabel.sizePolicy().hasHeightForWidth())
        self.launchHistoryLengthLabel.setSizePolicy(sizePolicy)
        self.launchHistoryLengthLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.launchHistoryLengthLabel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.launchHistoryLengthLabel.setObjectName("launchHistoryLengthLabel")
        self.gridLayout_4.addWidget(self.launchHistoryLengthLabel, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 2, 1, 1)
        self.launchHistoryLengthEdit = QtGui.QSpinBox(self.frameLaunchHistoryLength)
        self.launchHistoryLengthEdit.setObjectName("launchHistoryLengthEdit")
        self.gridLayout_4.addWidget(self.launchHistoryLengthEdit, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frameLaunchHistoryLength)
        self.frameParamHistoryLength = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameParamHistoryLength.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameParamHistoryLength.setFrameShadow(QtGui.QFrame.Raised)
        self.frameParamHistoryLength.setObjectName("frameParamHistoryLength")
        self.gridLayout_5 = QtGui.QGridLayout(self.frameParamHistoryLength)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.paramHistoryLengthLabel = QtGui.QLabel(self.frameParamHistoryLength)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramHistoryLengthLabel.sizePolicy().hasHeightForWidth())
        self.paramHistoryLengthLabel.setSizePolicy(sizePolicy)
        self.paramHistoryLengthLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.paramHistoryLengthLabel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.paramHistoryLengthLabel.setObjectName("paramHistoryLengthLabel")
        self.gridLayout_5.addWidget(self.paramHistoryLengthLabel, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 2, 1, 1)
        self.paramHistoryLengthEdit = QtGui.QSpinBox(self.frameParamHistoryLength)
        self.paramHistoryLengthEdit.setObjectName("paramHistoryLengthEdit")
        self.gridLayout_5.addWidget(self.paramHistoryLengthEdit, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frameParamHistoryLength)
        self.frameViewFileExt = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameViewFileExt.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameViewFileExt.setFrameShadow(QtGui.QFrame.Raised)
        self.frameViewFileExt.setObjectName("frameViewFileExt")
        self.gridLayout_6 = QtGui.QGridLayout(self.frameViewFileExt)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.viewFileExtLabel = QtGui.QLabel(self.frameViewFileExt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewFileExtLabel.sizePolicy().hasHeightForWidth())
        self.viewFileExtLabel.setSizePolicy(sizePolicy)
        self.viewFileExtLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.viewFileExtLabel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.viewFileExtLabel.setObjectName("viewFileExtLabel")
        self.gridLayout_6.addWidget(self.viewFileExtLabel, 0, 0, 1, 1)
        self.viewFileExtEdit = QtGui.QLineEdit(self.frameViewFileExt)
        self.viewFileExtEdit.setObjectName("viewFileExtEdit")
        self.gridLayout_6.addWidget(self.viewFileExtEdit, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frameViewFileExt)
        self.frameFollowFileExt = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameFollowFileExt.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameFollowFileExt.setFrameShadow(QtGui.QFrame.Raised)
        self.frameFollowFileExt.setObjectName("frameFollowFileExt")
        self.gridLayout_7 = QtGui.QGridLayout(self.frameFollowFileExt)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.followFileExtLabel = QtGui.QLabel(self.frameFollowFileExt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.followFileExtLabel.sizePolicy().hasHeightForWidth())
        self.followFileExtLabel.setSizePolicy(sizePolicy)
        self.followFileExtLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.followFileExtLabel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.followFileExtLabel.setObjectName("followFileExtLabel")
        self.gridLayout_7.addWidget(self.followFileExtLabel, 0, 0, 1, 1)
        self.followFileExtEdit = QtGui.QLineEdit(self.frameFollowFileExt)
        self.followFileExtEdit.setObjectName("followFileExtEdit")
        self.gridLayout_7.addWidget(self.followFileExtEdit, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frameFollowFileExt)
        self.frameStoreGeometry = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameStoreGeometry.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameStoreGeometry.setFrameShadow(QtGui.QFrame.Raised)
        self.frameStoreGeometry.setObjectName("frameStoreGeometry")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frameStoreGeometry)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setContentsMargins(1, 0, 1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.storeGeometryLabel = QtGui.QLabel(self.frameStoreGeometry)
        self.storeGeometryLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.storeGeometryLabel.setObjectName("storeGeometryLabel")
        self.horizontalLayout_2.addWidget(self.storeGeometryLabel)
        self.storeGeometryButton = QtGui.QCheckBox(self.frameStoreGeometry)
        self.storeGeometryButton.setText("")
        self.storeGeometryButton.setChecked(True)
        self.storeGeometryButton.setObjectName("storeGeometryButton")
        self.horizontalLayout_2.addWidget(self.storeGeometryButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.clearGeometryButton = QtGui.QPushButton(self.frameStoreGeometry)
        self.clearGeometryButton.setObjectName("clearGeometryButton")
        self.horizontalLayout_2.addWidget(self.clearGeometryButton)
        self.verticalLayout_2.addWidget(self.frameStoreGeometry)
        spacerItem3 = QtGui.QSpacerItem(20, 256, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.settingsTreeView = QtGui.QTreeView(self.dockWidgetContents)
        self.settingsTreeView.setObjectName("settingsTreeView")
        self.verticalLayout.addWidget(self.settingsTreeView)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(QtGui.QApplication.translate("DockWidget", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultUserLabel.setText(QtGui.QApplication.translate("DockWidget", "Default user:", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsPathLabel.setText(QtGui.QApplication.translate("DockWidget", "Settings path:", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsPathButton.setText(QtGui.QApplication.translate("DockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.robotPathButton.setText(QtGui.QApplication.translate("DockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.robotPathLabel.setToolTip(QtGui.QApplication.translate("DockWidget", "<html><head/><body><p>The path to the folder with robot images (<span style=\" font-weight:600;\">.png</span>). The images with robot name will be displayed in the info bar.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.robotPathLabel.setText(QtGui.QApplication.translate("DockWidget", "Robot icon path:", None, QtGui.QApplication.UnicodeUTF8))
        self.launchHistoryLengthLabel.setToolTip(QtGui.QApplication.translate("DockWidget", "<html><head/><body><p>The count of recent loaded launch files displayed in the root of the <span style=\" font-weight:600;\">launch files</span> view.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.launchHistoryLengthLabel.setText(QtGui.QApplication.translate("DockWidget", "Launch history length:", None, QtGui.QApplication.UnicodeUTF8))
        self.paramHistoryLengthLabel.setToolTip(QtGui.QApplication.translate("DockWidget", "<html><head/><body><p>The count of parameters stored which are entered in a parameter dialog (Launch file arguments, paramter server, publishing to a topic, service call)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.paramHistoryLengthLabel.setText(QtGui.QApplication.translate("DockWidget", "Param history length:", None, QtGui.QApplication.UnicodeUTF8))
        self.viewFileExtLabel.setToolTip(QtGui.QApplication.translate("DockWidget", "<html><head/><body><p>Files displayed in <span style=\" font-weight:600;\">launch files</span> view</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.viewFileExtLabel.setText(QtGui.QApplication.translate("DockWidget", "View file extentions:", None, QtGui.QApplication.UnicodeUTF8))
        self.followFileExtLabel.setToolTip(QtGui.QApplication.translate("DockWidget", "<html><head/><body><p>Files which are classified as <span style=\" font-weight:600;\">included file</span> in launch files.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.followFileExtLabel.setText(QtGui.QApplication.translate("DockWidget", "Follow file extentions:", None, QtGui.QApplication.UnicodeUTF8))
        self.storeGeometryLabel.setText(QtGui.QApplication.translate("DockWidget", "Store window layout:", None, QtGui.QApplication.UnicodeUTF8))
        self.clearGeometryButton.setToolTip(QtGui.QApplication.translate("DockWidget", "<html><head/><body><p>Deletes the current stored geometry settings.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.clearGeometryButton.setText(QtGui.QApplication.translate("DockWidget", "Clear", None, QtGui.QApplication.UnicodeUTF8))

